### ISSUE TITLE
When will the latent-variable model be publiced?

### ISSUE THREAD

**Issue by kyoto7250** [ictnlp/PLUVR#3]
Hi, thanks for your great research!

> Besides, for training of the latent-variable model, the visual features of all grounded regions are needed. We will release it soon, and you can extract them using scripts in the visual_grounding/ folder now.

I would like to train your model too.

When will the latent-variable model be publiced? :)

Best regards.

P.S

I think ACL just finished, so if you could just tell me when it is, that would be great.

**Comment by Poeroz** [comment]
Hi, thanks for your interest in our work! 

Sorry I haven't released the file until now, because currently I can only access the server via a VPN with limited bandwidth due to the policy of Covid-19... which makes it difficult for me to transfer such a large file from the server. 

Hopefully I can do it in the next one or two months. You can try to extract the visual features with scripts under the `visual_grounding/` folder. Sorry again for the inconvenience.

**Comment by kyoto7250** [comment]
Thank you for your quick reply!

> Sorry I haven't released the file until now, because currently I can only access the server via a VPN with limited bandwidth due to the policy of Covid-19... which makes it difficult for me to transfer such a large file from the server.


I understood. 
That sounds tough.😰

> Hopefully I can do it in the next one or two months. You can try to extract the visual features with scripts under the visual_grounding/ folder. Sorry again for the inconvenience.

I'll check it, thanks so much !👍🏻
